### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by bwsperry** [echonet/lvh#14]
Hi, when I run this from Windows command prompt, I get the following error. Can someone help troubleshoot? Thanks

run_plax_hypertrophy_inference.py ./PLAX ./Inference

Traceback (most recent call last):
  File "C:\EchoNET\LVH\run_plax_hypertrophy_inference.py", line 375, in <module>
    args.update({k.replace('-', '_'): v for k, (v, h) in vars(parser.parse_args()).items()})
  File "C:\EchoNET\LVH\run_plax_hypertrophy_inference.py", line 375, in <dictcomp>
    args.update({k.replace('-', '_'): v for k, (v, h) in vars(parser.parse_args()).items()})
ValueError: too many values to unpack (expected 2)

**Comment by bwsperry** [comment]
I see that this was discussed in another issue and have made this change:
args.update({k.replace('-', '_'): v for k, v in vars(parser.parse_args()).items()})
get_args = lambda l: {k: args[k] for k in l}

Unfortunately, now I'm getting this error:
TypeError: <lambda>() takes 1 positional argument but 2 were given

**Comment by musc-zhangru** [comment]
This works for me: 

 # Run inference
engine = PlaxHypertrophyInferenceEngine(**get_args(['device', 'model_path']))
engine.run_on_dir(**get_args(['in_dir', 'out_dir', 'batch_size', 'n_threads', 'verbose', 'save_csv', 'save_avi', 'save_npy']))

**Comment by k2aitechno** [comment]
Is anyone getting weights error after above fixes?
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ritikagrawal/echo_1/venv/lvh/weights/hypertrophy_model.pt'

Looks like the weights are not present in the current repo.
